# Generated by Django 5.2.3 on 2025-07-01 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("motoristas", "0001_initial"),
        ("veiculos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioDisponivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("hora_inicio", models.TimeField(verbose_name="Hora início")),
                ("hora_fim", models.TimeField(verbose_name="Hora fim")),
                (
                    "disponivel",
                    models.BooleanField(default=True, verbose_name="Disponível"),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="motoristas.motorista",
                        verbose_name="Motorista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário Disponível",
                "verbose_name_plural": "Horários Disponíveis",
                "ordering": ["data", "hora_inicio"],
                "unique_together": {("data", "hora_inicio", "hora_fim", "motorista")},
            },
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_solicitante",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Solicitante"
                    ),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                ("ramal", models.CharField(max_length=20, verbose_name="Ramal")),
                (
                    "data_solicitacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da solicitação"
                    ),
                ),
                (
                    "finalidade",
                    models.CharField(
                        choices=[
                            ("SERVICO_ADMINISTRATIVO", "Serviço Administrativo"),
                            ("SERVICO_CAMPO", "Serviço de Campo"),
                            ("AEROPORTO", "Aeroporto"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Finalidade da solicitação",
                    ),
                ),
                (
                    "tipo_veiculo",
                    models.CharField(
                        choices=[
                            ("CARRO", "Carro"),
                            ("MOTO", "Moto"),
                            ("UTILITARIO", "Utilitário"),
                            ("PICKUP", "Pick up"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Veículo",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        help_text="Digite o CEP para carregar o endereço automaticamente (opcional)",
                        max_length=9,
                        verbose_name="CEP",
                    ),
                ),
                (
                    "destino_endereco",
                    models.CharField(max_length=200, verbose_name="Destino/Endereço"),
                ),
                (
                    "descricao_servico",
                    models.TextField(verbose_name="Descrição do serviço"),
                ),
                (
                    "data_realizacao",
                    models.DateField(verbose_name="Data para realização do serviço"),
                ),
                ("hora_saida", models.TimeField(verbose_name="Hora saída")),
                (
                    "hora_retorno",
                    models.TimeField(verbose_name="Hora retorno (Previsão)"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "chefia_imediata",
                    models.CharField(max_length=100, verbose_name="Chefia imediata"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADA", "Aprovada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de aprovação"
                    ),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_aprovadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitacoes.horariodisponivel",
                        verbose_name="Horário",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veiculos.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação",
                "verbose_name_plural": "Solicitações",
                "ordering": ["-data_solicitacao"],
            },
        ),
    ]
