# Generated by Django 5.2.3 on 2025-06-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitacoes", "0002_solicitacao_nome_solicitante"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="cep",
            field=models.CharField(
                default=0,
                help_text="Digite o CEP para carregar o endereço automaticamente",
                max_length=9,
                verbose_name="CEP",
            ),
            preserve_default=False,
        ),
    ]
