# Generated by Django 5.2.3 on 2025-07-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitacoes", "0003_solicitacao_cep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacao",
            name="cep",
            field=models.CharField(
                blank=True,
                help_text="Digite o CEP para carregar o endereço automaticamente (opcional)",
                max_length=9,
                verbose_name="CEP",
            ),
        ),
    ]
